### ISSUE TITLE
Error! Failed to initialize.

### ISSUE THREAD

**Issue by vicfixxx** [esphome/esp-web-tools#118] opened 2021-11-14 01:20 UTC
When i click the install button in the WLED application, i get the following response:

Failed to initialize. Try resetting your device or holding the BOOT button while selecting your serial port.

I have a ESP8266 chip and i also tried ESP home and Tasmota, both gave the same issue.

**Comment by balloob** [comment] 2021-11-14 04:09
What device?

Does it have a BOOT button?

Did you hold it while pressing install?

**Comment by vicfixxx** [comment] 2021-11-14 07:03
Hi,

I use the AZDelivery D1 Mini NodeMcu met ESP8266-12F and unfortunatly it doesn't have a BOOT button.

If i try to install something different, it works. I also tried with a brand new device, and get the same error message.

**Comment by TD-er** [comment] 2021-11-14 12:14
Does the serial port show up in the task manager? And is it still present when the failure appeared?
I've seen a few of those that had really flaky USB connectors.
You may also try a different USB cable and/or connect it directly to an USB port on the PC instead of via a hub.

**Comment by vicfixxx** [comment] 2021-11-14 14:45
I can see the device in my device manager with a COM port (currently COM 4).

I've tried a couple of USB cables and i can see the device in the device manager, so that should be good.

I've attached the specific error on the webpage.

The funny thing is that i've tried on a different computer and i get the same error.

Should i check the COM settings, like BAUT rate? if so, do you know what data i have to use?


Thanks in advance ;)

![error ESP](https://user-images.githubusercontent.com/69636400/141685943-439989d2-7193-451a-bf3a-4c68bb8387d4.PNG)
.

**Comment by vicfixxx** [comment] 2021-11-15 19:25
Hi, I probably applied too much heat to the board during soldering, so I've ordered some new ones and try it out on those. As soon as i know more, i'll let you know 😎

**Comment by balloob** [comment] 2022-03-08 07:34
Closing this issue as this is based on an old version of ESP Web Tools.

**Closed by balloob** 2022-03-08 07:34 UTC

**Comment by adman120** [comment] 2022-03-17 01:41
Can you reopen the issue, it is still happening, on current version for me, with same model esp.

**Comment by balloob** [comment] 2022-03-17 04:59
Please open a new issue and include logs + model and steps you did to reproduce.

**Comment by adman120** [comment] 2022-03-17 11:51
Will do, no problem.

**Comment by Oinq** [comment] 2022-11-23 20:58
Where did u opened it? I'm facing the same described above with the same hardware.

**Comment by finnfreijer** [comment] 2023-02-12 12:03
hallo ik heb een esp32 en ik probeer wled er op te downloaden maar elke keer als ik dat probeer geeft die aan dat ik de boot knop moet in drukken maar als ik dat doe verandert er niks. wat moet ik doen???

**Comment by MichalKrasowski** [comment] 2023-07-24 07:57
In my case it was lack of privileges for `/dev/ttyUSB0`.

Granting access to all ( `sudo chmod 777 /dev/ttyUSB0`) proves it's privileges issue.

Relevant devtools log on failure:
`:673  DOMException: Failed to execute 'open' on 'SerialPort': Failed to open serial port.
_handleConnectSerialSubmit @ wi`

**Comment by phanky5** [comment] 2023-08-17 20:13
Thank you @MichalKrasowski this solved the issue for me.

**Comment by Id2ndR** [comment] 2024-04-22 15:32
Granting access to other (`sudo chmod o+rw /dev/ttyUSB0`) temporary solve the privileges issue. The 'x' permission is not required.

To permanently solve this, you must add yourself in the group associated to this `/dev/ttyUSB0` file.
This can be done with the following command followed by a restart of you session: `sudo usermod -a -G $(stat -c %G /dev/ttyUSB0) $(whoami)`

**Comment by skyfly200** [comment] 2026-01-15 18:10
Im having this issue now with my ESP32-S2 on a windows machine. Not sure what to do since I dont have the linux env to try this solution.
